name: Publish to Feishu Bitable

on:
  #workflow_run:
  #  workflows: ["Generate Markdown"]
  #  types: [completed]
  workflow_dispatch:  # 手动触发

jobs:
  publish_to_feishu_bitable:
    runs-on: ubuntu-latest
    env:
      PUBLISH_ENABLED: 'true'  # 设置环境变量，控制是否启用发布

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: ${{ env.PUBLISH_ENABLED == 'true' }}  
      run: |
        pip install aiohttp
        pip install python-dotenv
        pip install pytz

    - name: Publish to Feishu Bitable
      if: ${{ env.PUBLISH_ENABLED == 'true' }}  
      env:
        FEISHU_APP_ID: ${{ secrets.FEISHU_APP_ID }}
        FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
        FEISHU_BITABLE_APP_TOKEN: ${{ secrets.FEISHU_BITABLE_APP_TOKEN }}
        FEISHU_BITABLE_TABLE_ID: ${{ secrets.FEISHU_BITABLE_TABLE_ID }}
      run: |
        python scripts/aibase_com/publish_to_feishu_bitable.py

    - name: Check for changes
      run: |
        git diff --exit-code || echo "Changes detected"

    - name: Commit files if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add .
        git commit -m "updated processed_records"

    - name: Push changes
      run: |
        git push --force https://${{ secrets.PAT }}@github.com/${{ github.repository_owner }}/ai-info-collector.git HEAD:main